# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

variables:
  bkstrgrg:'rp0041-rg'
  bkstrg:'rp0041sa'
  bkcontainer:'tfstate'
  bkstrgkey:'tf001.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        displayName: 'Terraform Validate'
        steps:
          - task: TerraformInstaller@1
            displayName: 'TF Install'
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: 'TF init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'rp0041-rg'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
          - task: TerraformTaskV4@4
            displayName: 'TF validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
