# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

parameters:
  - name: targetEnvironment
    displayName: "Target Environment"
    type: string
    default: dev
    values:
      - dev
      - test
      - acc

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        displayName: 'Terraform Validate'
        steps:
          - task: Bash@3
            displayName: 'Check TF version'
            inputs:
              targetType: 'inline'
              script: |
                echo "Bash"
                terraform -v
                pwd
                ls -ltrh
          - task: Bash@3
            displayName: 'Init - Dev'
            condition: eq(variables['targetEnvironment'],'dev')
            inputs:
              targetType: 'inline'
              script: |
                terraform init -backend-config=./environment/backend_d.conf
          - task: Bash@3
            displayName: 'Init - Test'
            condition: eq(variables['targetEnvironment'],'test')
            inputs:
              targetType: 'inline'
              script: |
                terraform init -backend-config=./environment/backend_t.conf
          - task: Bash@3
            displayName: 'Init - Acc'
            condition: eq(variables['targetEnvironment'],'acc')
            inputs:
              targetType: 'inline'
              script: |
                terraform init -backend-config=./environment/backend_a.conf
          - task: Bash@3
            displayName: 'Validate'
            inputs:
              targetType: 'inline'
              script: |
                terraform validate
          - task: Bash@3
            displayName: 'Plan - Dev'
            inputs:
              targetType: 'inline'
              script: |
                terraform plan -var-file ./environment/dev.tfvars
          - task: Bash@3
            displayName: 'List files'
            inputs:
              targetType: 'inline'
              script: |
                pwd
                ls -ltrh
