# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

variables:
  bkstrgrg: 'rp0041-rg'
  bkstrg: 'rp0041sa'
  bkcontainer: 'tfstate'
  bkstrgkey: 'tf001.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        displayName: 'Terraform Validate'
        steps:
          - task: Bash@3
            displayName: 'Check TF version'
            inputs:
              targetType: 'inline'
              script: |
                echo "Bash"
                terraform -v
                pwd
                ls -ltrh
          - task: Bash@3
            displayName: 'Init'
            inputs:
              targetType: 'inline'
              script: |
                terraform init
          - task: Bash@3
            displayName: 'Validate'
            inputs:
              targetType: 'inline'
              script: |
                terraform validate
          - task: Bash@3
            displayName: 'Plan'
            inputs:
              targetType: 'inline'
              script: |
                terraform plan
          - task: Bash@3
            displayName: 'List files'
            inputs:
              targetType: 'inline'
              script: |
                pwd
                ls -ltrh
